### ISSUE TITLE
Licence in some files doesn't match project licence

### ISSUE THREAD

**Issue by sam-bristow** [micro-os-plus/posix-arch#1]
The overall licence (in LICENCE.md) for this project is listed as the MIT licence. However, many of the individual files have LGPL3 licence headers. Is this intentional, or just an oversight?

### LGPL3
src/diag/trace-posix.cpp
test/trace-stderr/main.cpp
test/trace-stdout/main.cpp

### MIT
src/rtos/os-core.cpp
include/cmsis-plus/rtos/port/os-c-decls.h
include/cmsis-plus/rtos/port/os-decls.h
include/cmsis-plus/rtos/port/os-inlines.h

**Comment by ilg-ul** [comment]
> LGPL3 licence ... Is this intentional?

oops! no, it is not intentional, I need to update it.

thank you for helping improve µOS++!

**Comment by ilg-ul** [comment]
fixed.
